title: Achim's Homepage
author: Achim Christ
collections:
  sections:
    output: false
compress_html:
  comments: all
exclude: [
  'Gemfile*',
  'Gruntfile.js',
  'img/src',
  'imgsrc',
  'node_modules',
  'package.json',
  'README.md']
width_fixed_col: col-12 col-md-10
width_full_col: col-12
width_half_col: col-12 col-md-5
canonical: https://www.achim-christ.de
